name: bagz_app
description: "A Bag shopping app"

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/appBar/
    - assets/latest_product_card/
    - assets/product_card/
    - assets/shop_by_categories_card/
    - assets/details_page/
    - assets/icons/
    - assets/bottom_modal_sheet/
  

  